"""Official GBP category pages. Copy is taken only from existing Option 1 pages."""

from gbp_extra import apply_extra

SERVICES = [
    {
        "slug": "landscaper",
        "anchor": "landscaper",
        "nav": "Landscaper",
        "h1": "Encino Landscaper for Residential Yards",
        "card_h3": "Landscaper",
        "tag": "Primary",
        "title": "Encino Landscaping Landscaper | Landscape Designer CA",
        "description": "Encino landscaper for residential yards: landscape design, install, irrigation, and drainage. Licensed landscape contractor #1122918. Call 818-297-2475.",
        "h2_includes": "Landscaping Services, Paver Work, and Retaining Walls for the Homeowner",
        "h2_estimate": "Free Consultation: How This Encino Landscape Contractor Estimates",
        "h2_related": "Nearby Areas and a Cohesive Project in Encino",
        "cta_h2": "Free Consultation for Encino Landscaping Services",
        "hero_chip": ("Since", "2002"),
        "highlights": [
            (
                "Licensed Encino landscaper",
                "Option 1 Builders is a licensed landscape contractor in Encino, CA under California license #1122918. You can verify that number with the CSLB.",
            ),
            (
                "In-house crews",
                "Turf, pavers, and concrete are installed by our own crews. One project manager runs the job from the walkthrough to cleanup.",
            ),
            (
                "Irrigation and drainage",
                "We install and modify sprinkler and drip systems and build drainage that moves water away from the house. On sloped Valley lots this protects everything else you are paying for.",
            ),
        ],
        "image": "project-05.jpg",
        "image_alt": "Full yard landscaping in Encino with turf and a paver walkway",
        "hero_sub": "Google's primary category for this Encino business is Landscaper. Eli and the crew design and install residential yards from Ventura Blvd across the San Fernando Valley.",
        "lead": "Option 1 Builders is an Encino landscaper. Our office is at 16400 Ventura Blvd, Suite 319. Homeowners hire this contractor for landscape design and landscape installation — artificial turf, pavers, driveways, irrigation, drainage, and full residential yards. More than 1,000 of them since 2002. Encino landscapers at this address do the install, not a rotating crew.",
        "lead_more": [
            "We build for families, not commercial landscaping. The outdoor yard, backyard, front yard, and garden get planned around where the dog runs, where the sun lands at four o'clock, and where you want a table. We do not sell weekly landscape maintenance. We install the landscape so a homeowner can use the yard without hiring a crew to mow.",
            "Most Encino homeowners who call already collected two or three quotes. The numbers do not match because the scopes do not match. We write demolition, base, material, edging, and drainage as separate lines on the estimate so you can see what a cheaper bid left out.",
        ],
        "article_extra": [
            "Landscapers in Encino at this address do landscape installation, not weekly lawn care or landscape maintenance. The outdoor space is a front yard, backyard, or garden planned around how you use it.",
            "A free consultation is the walkthrough. We measure, talk through irrigation and planting, and send a written scope. Services in Encino include pavers, retaining walls when the yard needs them, and the same contractor from the first visit to cleanup.",
            "Start with a free consultation if you want this Encino landscaper to walk the property this week. Call 818-297-2475.",
        ],
        "blocks": [
            (
                "Residential yards, not a template",
                "A landscaper who treats your lot like a template cannot plan around how you use the space. We walk the property, measure on site, and send a written number tied to a specific spec.",
            ),
            (
                "Irrigation and drainage on the same crew",
                "Sprinkler and drip systems, and yard drains that move water off the property. Irrigation parts we buy include Rain Bird and Hunter, with NDS drainage products, so you can still get parts years from now.",
            ),
            (
                "Hire one line or the whole yard",
                "Artificial grass, pavers, stepping stones, DG, irrigation, and fencing can each be quoted on their own. A full yard combines them under one project manager.",
            ),
            (
                "License on the walkthrough table",
                "We hand you a copy of the license, insurance, and liability paperwork at the estimate. Professional care of your property starts there, not after demo.",
            ),
        ],
        "card_p": "Google's primary category. Encino landscaper for residential yards: design, install, irrigation, and drainage under contractor license #1122918.",
        "card_meta": ("Primary GBP category", "Residential landscape design and installation, plus irrigation and drainage."),
        "faqs": [
            ("Are you licensed and insured?", "Yes. Option 1 Builders is a licensed, bonded, and insured contractor under California license #1122918. You can verify that license with the CSLB. We hand you a copy of the license and insurance at the walkthrough before any landscape work starts."),
            ("Do you handle irrigation and drainage?", "Yes. We install and modify sprinkler and drip systems and build drainage that moves water away from the house and off the property. On sloped Valley lots this is usually the part that protects everything else you are paying for."),
            ("Do you use subcontractors?", "No. Turf, pavers, and concrete are installed by our own crews. That is how we control compaction, seams, and the final walkthrough instead of hoping a rotating crew shows up."),
            ("Can I hire just one service?", "Yes. Artificial grass, pavers, stepping stones, DG, irrigation, and fencing can each be quoted on their own. A full yard combines them under one project manager."),
            ("Where is the company based?", "Our office and showroom are at 16400 Ventura Blvd, Suite 319, Encino, CA 91436. Hours are Monday through Sunday, 8:00 AM to 6:00 PM. We are landscapers in Encino, not a commercial-property crew."),
        ],
        "related": ["landscape-designer", "turf-and-soil-supplier", "construction-company"],
        "closing_h2": "Ready to Hire This Encino Landscaper?",
        "closing_p": "If you want an Encino landscaper that writes the base depth down before demo starts, call 818-297-2475 or request a free estimate. We will walk your property this week and send a written quote.",
    },
    {
        "slug": "remodeller",
        "anchor": "remodeller",
        "nav": "Remodeller",
        "h1": "Outdoor Remodel in Encino for Backyard Living",
        "card_h3": "Remodeller",
        "tag": "Outdoor",
        "title": "Outdoor Remodel Encino CA | Backyard Remodel",
        "description": "Outdoor remodel in Encino for backyard rebuilds: turf, pavers, patio, planting, and drainage. Not interior house remodeling. Call 818-297-2475.",
        "h2_includes": "Backyard Remodel in Encino: Patio, Turf, Walkway, and Transformation",
        "h2_estimate": "Outdoor Renovation Estimate for an Encino Backyard Remodel",
        "h2_related": "Remodeling Services in Encino Beside This Outdoor Renovation",
        "cta_h2": "Free Consultation for Remodeling Encino Outdoor Space",
        "highlights": [
            (
                "Outdoor yards only",
                "Remodeller work here is a front and back yard rebuild, not a kitchen, bath, or interior house remodel.",
            ),
            (
                "One plan, one crew",
                "Front and back yard work combines turf, hardscape, planting, irrigation, and drainage into one plan and one crew.",
            ),
        ],
        "image": "project-01.jpg",
        "image_alt": "Paver and turf patio with pool deck and outdoor bar on a finished Encino yard",
        "media_frame": True,
        "hero_sub": "Google lists Remodeller as a category for this Encino landscaper. That means outdoor yard rebuilds — not interior house remodeling.",
        "lead": "Option 1 Builders designs and installs full yards in Encino so the finished yard reads as a single design instead of three separate jobs. A full front-and-back transformation with irrigation, drainage, and hardscape can take several weeks. Your written proposal includes the expected timeline.",
        "lead_more": [
            "Jobs here run from a single turf lawn to a full front-and-back rebuild with pavers, drainage and planting. One project manager runs the work from the walkthrough to cleanup.",
            "We write demolition, base, material, edging, and drainage as separate lines so you can see what a cheaper bid left out. A cheaper quote that skips drainage is not the same job.",
        ],
        "article_extra": [
            "An outdoor remodel here is outdoor living: patio, driveway when the job needs pavers, artificial turf, and hardscape. It is a backyard remodel or a front-and-back renovation, not an interior remodeling service.",
            "Homeowners comparing remodeling services in Encino should ask every contractor the same three questions: how deep is the base, how does water leave the yard, and who is on site each day. We answer all three in writing before demolition.",
            "A free consultation starts the outdoor renovation. Call 818-297-2475 and we will walk the Encino backyard this week.",
        ],
        "blocks": [
            (
                "What a yard remodel covers",
                "Grading, drainage, irrigation, planting, hardscape, and lighting — scheduled so no trade undoes another's work.",
            ),
            (
                "Not an interior remodel",
                "We do not remodel kitchens, bathrooms, or the inside of the house. Remodeller on this site means the outdoor yard: front yard, backyard, and garden.",
            ),
            (
                "Timeline already on the site",
                "A front yard turf replacement is often a few days. A larger back yard or a lawn paired with pavers usually runs about one to two weeks. A full front-and-back transformation can take several weeks.",
            ),
        ],
        "card_p": "Outdoor yard rebuilds: turf, hardscape, planting, irrigation, and drainage under one crew. Not interior house remodeling.",
        "card_meta": ("Outdoor only", "Full front and back yard transformations, not kitchens or baths."),
        "faqs": [
            ("Do you remodel the inside of the house?", "No. Remodeller work at Option 1 Builders is outdoor yards. We rebuild front and back yards. We do not remodel kitchens, bathrooms, or interior rooms."),
            ("Can I hire just one service?", "Yes. Artificial grass, pavers, stepping stones, DG, irrigation, and fencing can each be quoted on their own. A full yard combines them under one project manager."),
            ("How long does a full yard take?", "A full front-and-back transformation with irrigation, drainage, and hardscape can take several weeks. Your written proposal includes the expected timeline."),
            ("Do you use subcontractors?", "No. Turf, pavers, and concrete are installed by our own crews."),
        ],
        "related": ["landscaper", "landscape-designer", "paving-contractor"],
        "closing_h2": "Ready to Price an Outdoor Yard Remodel?",
        "closing_p": "Tell us you want a full yard plan. We will walk the property and send a written scope for an outdoor remodel in Encino. Call 818-297-2475 or request a free estimate.",
    },
    {
        "slug": "turf-and-soil-supplier",
        "anchor": "turf",
        "nav": "Turf and Soil Supplier",
        "h1": "Artificial Grass Installation in Encino, California",
        "card_h3": "Turf and Soil Supplier",
        "tag": "Turf",
        "title": "Artificial Turf Installation Encino | Artificial Grass",
        "description": "Artificial grass installation in Encino: synthetic turf, pet turf, putting greens, and a compacted draining base. Not a retail shop. Call 818-297-2475.",
        "h2_includes": "Artificial Turf Installation, Pet Turf, and Putting Green Infill",
        "h2_estimate": "Installation From Start to Finish for Encino Homeowners",
        "h2_related": "Synthetic Turf Installation and Turf Services Beside This Lawn",
        "cta_h2": "Request a Free Artificial Grass Installation Estimate",
        "hero_chip": ("15-year", "turf warranty"),
        "highlights": [
            (
                "15-year turf warranty",
                "Every artificial grass installation we complete is backed by a 15-year warranty, written into the scope at the estimate.",
            ),
            (
                "Pet-permeable base",
                "Pet installations use a permeable base and drainage layer so urine passes through, plus infill chosen for pet use.",
            ),
            (
                "Not a retail shop",
                "Turf and soil work is installation and the compacted base under the lawn. We buy turf products from suppliers including Turf Distributors. We are not a walk-in turf or soil store.",
            ),
        ],
        "blog_note": (
            "../../blog/index.html#turf-base",
            "what a cheap turf bid usually leaves out",
        ),
        "image": "project-02.jpg",
        "image_alt": "Artificial grass installation on an Encino front lawn",
        "media_frame": True,
        "hero_sub": "Google lists Turf and Soil Supplier as a category. On this site that means artificial grass installation and the compacted base under it — not a supply store.",
        "lead": "Option 1 Builders installs artificial grass in Encino and across the San Fernando Valley. We remove the old lawn, compact a draining base, then seam, nail, and infill so the lawn stays flat. Every artificial grass installation we complete is backed by a 15-year warranty.",
        "lead_more": [
            "The number on a turf bid is not the pile height. It is the base. If the estimate does not name demolition, compaction, drainage, and edge restraint as separate lines, you are comparing a lawn to a rug.",
            "Turf products come from suppliers we already buy from, including Turf Distributors. You can compare turf pile and color at the Encino showroom at 16400 Ventura Blvd, Suite 319. We do not sell bags of soil or rolls of turf over a counter.",
        ],
        "article_extra": [
            "Option 1 Builders does artificial grass installation in Encino and across the San Fernando Valley. Licensed, bonded, and insured installers have finished more than 1,000 yards since 2002. We also install paver patios and complete front and back yards.",
            "Homeowners call us when a natural grass lawn is failing in Valley heat. We remove that lawn - the one you have to mow and water - then do turf installation with synthetic turf or synthetic grass. The turf surface stays green without reseeding. Pet turf uses a permeable base and infill chosen for dogs. Putting green installation and custom putting greens are quoted on their own.",
            "A front yard or a full landscape gets the same process from start to finish. Artificial turf installation and synthetic turf installation use a compacted base so water drains. That is curb appeal on Encino properties - the lawn neighbors see from the street.",
            "Premium synthetic turf and premium artificial turf installation still fail if the base is wrong. We do not quote a per square foot number before we walk the property. A free consultation is the walkthrough. Installation services in Encino are residential, not commercial.",
            "Artificial grass in Encino and turf installation Encino jobs use the same installer: one project manager, in-house crews, written scope. Grass installation in Encino for a front yard is often a few days. Installation in Encino for a lawn paired with pavers usually runs one to two weeks.",
        ],
        "blocks": [
            (
                "Lawn removal, base, and infill",
                "Pet-friendly and putting-green turf for front yards, back yards, side yards, and play areas. We remove the old lawn, install a compacted base for drainage, then seam, nail, and infill so the turf stays flat and cool underfoot.",
            ),
            (
                "Common jobs",
                "Front lawn replacement, backyard putting greens, dog runs, shaded side yards, and tear-outs of turf laid over the wrong base the first time.",
            ),
            (
                "The base is the bid",
                "We measure on site and give you a written number tied to a specific material and base spec instead of a per-foot guess over the phone.",
            ),
            (
                "Soil and base, not a store",
                "The soil work is the compacted, draining base under synthetic turf. We are a Turf and Soil Supplier in the Google sense because we install that system. We are not a retail turf or soil shop.",
            ),
        ],
        "card_p": "Artificial grass installation and the compacted base under it. We buy from Turf Distributors. We are not a retail turf or soil store.",
        "card_meta": ("Install and base", "Pet turf, putting greens, lawn replacement, and base repair. 15-year warranty."),
        "faqs": [
            ("How long does artificial grass installation take?", "A front yard turf replacement is often a few days. A larger back yard or a lawn paired with pavers usually runs about one to two weeks. A full front-and-back transformation with irrigation, drainage, and hardscape can take several weeks. Your written proposal includes the expected timeline."),
            ("Is your artificial turf safe for dogs?", "Yes. Pet installations use a permeable base and drainage layer so urine passes through instead of pooling, plus infill chosen for pet use. Tell us at the walkthrough that you have dogs so the base is built for it from the start."),
            ("Can you replace old artificial turf?", "Yes. We remove and dispose of the existing turf, inspect the base underneath, correct any drainage or compaction problems we find, then install the new turf. Reusing a failed base is the most common reason a second turf job goes wrong."),
            ("Do you sell turf or soil by the bag?", "No. Turf and soil work is installation and the compacted base under the lawn. Visit the Encino showroom to compare turf pile and color. We do not run a retail supply counter."),
            ("What does the 15-year warranty cover?", "Every artificial grass installation we complete is backed by a 15-year warranty. We walk the coverage with you at the estimate so you know what is included before you sign, and we put it in the written scope."),
        ],
        "related": ["landscaper", "paving-contractor", "landscape-designer"],
        "closing_h2": "Ready for Grass Installation in Encino?",
        "closing_p": "Tell us about the yard. We will walk the property, write the base and drainage into the scope, and send a written number for artificial grass installation in Encino. Call 818-297-2475 or request a free estimate.",
    },
    {
        "slug": "paving-contractor",
        "anchor": "pavers",
        "nav": "Paving contractor",
        "h1": "Paving Contractor in Encino for Driveways and Pavers",
        "card_h3": "Paving contractor",
        "tag": "Hardscape",
        "title": "Paving Contractor in Encino | Pave Paver Driveway",
        "description": "Paving contractor in Encino for paver driveways, walkways, and patios on a compacted base with bedding sand and edge restraints. Call 818-297-2475.",
        "h2_includes": "Pave Encino Driveways: Paver, Walkway, Patio, and Pool Deck",
        "h2_estimate": "How Homeowners Hire a Paving Contractor in Encino",
        "h2_related": "Concrete Services, Stamped Concrete, and New Asphalt We Do Not Pour",
        "cta_h2": "Request a Free Paving Contractor Estimate for Paving in Encino",
        "highlights": [
            (
                "Compacted base and restraints",
                "Pavers are set on a compacted base with bedding sand and edge restraints, which is what keeps them from shifting.",
            ),
        ],
        "image": "project-09.jpg",
        "image_alt": "Paver driveway installation at a Los Angeles area home",
        "media_frame": True,
        "hero_sub": "Google lists Paving contractor as a category. We install paver patios, walkways, driveways, and pool decks. Correct base depth, bedding sand, and edge restraints keep pavers from shifting.",
        "lead": "Option 1 Builders installs pavers and hardscape in Encino. Pavers are set on a compacted base with bedding sand and edge restraints, which is what keeps them from shifting or sinking later. That is where the labor goes.",
        "lead_more": [
            "Correct base depth, bedding sand, and edge restraints are what keep pavers from shifting, so that is where we spend the labor other bids skip.",
        ],
        "article_extra": [
            "Paving contractors in Encino who skip the base are not bidding the same driveway. We set paving stone and interlocking pavers for driveway paving, walkway, and patio work. We do not pour asphalt paving or pave parking lots.",
            "Paving in Encino on a residential lot is curb appeal: the driveway and walkway neighbors see from the street. Homeowners hire this paving contractor for pavers, not asphalt.",
            "A free consultation is the walkthrough. We measure the driveway or patio, write the base and edge restraints, and send a written scope. Call 818-297-2475.",
            "Paving services here sit next to Construction Company hardscape and the Encino landscaper page. You can hire paving on its own or with turf.",
        ],
        "blocks": [
            (
                "What we set",
                "Interlocking pavers, natural stone, and poured concrete across patios, walkways, driveways, pool decks, retaining walls, and seat walls.",
            ),
            (
                "Why the base matters",
                "Pavers are set on a compacted base with bedding sand and edge restraints. If that line is missing from a bid, the cheaper number is not the same job.",
            ),
            (
                "Materials you can see",
                "Visit the Encino showroom at 16400 Ventura Blvd, Suite 319 to compare paver styles at full size. We buy from ORCO, Belgard, and Angelus Block.",
            ),
        ],
        "card_p": "Paver patios, walkways, driveways, and pool decks. Compacted base, bedding sand, and edge restraints so pavers stay level.",
        "card_meta": ("What we set", "Interlocking pavers, natural stone, and poured concrete across patios, walkways, driveways, and seat walls."),
        "faqs": [
            ("Do you install pavers and concrete?", "Yes. We install paver patios, walkways, driveways, pool decks, and retaining walls, along with poured concrete. Pavers are set on a compacted base with bedding sand and edge restraints, which is what keeps them from shifting or sinking later."),
            ("Can I see materials before I decide?", "Yes. Visit the Encino showroom at 16400 Ventura Blvd, Suite 319 to compare turf pile and color, paver styles, and finish materials at full size. Photos on a phone screen rarely match how a material reads across a whole yard."),
            ("Can I hire just one service?", "Yes. Artificial grass, pavers, stepping stones, DG, irrigation, and fencing can each be quoted on their own. A full yard combines them under one project manager."),
        ],
        "related": ["construction-company", "landscaper", "turf-and-soil-supplier"],
        "closing_h2": "Ready to Price Paving in Encino?",
        "closing_p": "Tell us whether you need a patio, walkway, driveway, or pool deck. We will walk the property and send a written scope for paver installation in Encino. Call 818-297-2475 or request a free estimate.",
    },
    {
        "slug": "landscape-designer",
        "anchor": "design",
        "nav": "Landscape designer",
        "h1": "Landscape Designer for Encino Yards",
        "card_h3": "Landscape designer",
        "tag": "Design",
        "title": "Landscape Designer Encino | Landscape Design Outdoor Living",
        "description": "Landscape designer in Encino for landscape design and build: one plan, one crew, outdoor living space. Licensed. Call 818-297-2475.",
        "h2_includes": "Landscape Design and Build, Irrigation, and Outdoor Living Space",
        "h2_estimate": "Free Consultation for Landscape Design and Build",
        "h2_related": "Not Landscape Architecture or Landscape Architects",
        "cta_h2": "Free Consultation for Landscape Design Services in Encino",
        "highlights": [
            (
                "One plan, one crew",
                "Front and back yard work combines turf, hardscape, planting, irrigation, and drainage into one plan and one crew.",
            ),
            (
                "Hire one line or the yard",
                "Artificial grass, pavers, stepping stones, DG, irrigation, and fencing can each be quoted on their own.",
            ),
        ],
        "image": "project-01.jpg",
        "image_alt": "Designed Encino yard with paver patio, turf, and outdoor living space",
        "hero_sub": "Google lists Landscape designer as a category. The plan is the job: turf, hardscape, planting, irrigation, and drainage scheduled so no trade undoes another's work.",
        "lead": "Option 1 Builders designs and installs full yards in Encino so the finished yard reads as a single design instead of three separate jobs. One project manager runs the work from the walkthrough to cleanup.",
        "lead_more": [
            "The outdoor yard and garden get planned around where the dog runs, where the sun lands at four o'clock, and where you want a table. A landscaper who treats your lot like a template cannot do that.",
        ],
        "article_extra": [
            "Landscape design services in Encino on this page are design and build: one landscaping project, one outdoor space, one crew. A free consultation starts the plan.",
            "Sustainable landscaping here means low-water finishes we already install: turf, DG, and drainage that moves water off the lot. We do not invent a new irrigation spec.",
        ],
        "blocks": [
            (
                "One plan covers",
                "Grading, drainage, irrigation, planting, hardscape, and lighting — scheduled so no trade undoes another's work.",
            ),
            (
                "How this differs from Landscaper",
                "Landscaper is the crew and the business. Landscape designer is the plan: one design, one material list, one schedule. Both pages describe work we already install.",
            ),
            (
                "Timeline",
                "A full front-and-back transformation with irrigation, drainage, and hardscape can take several weeks. Your written proposal includes the expected timeline.",
            ),
        ],
        "card_p": "One plan and one crew for turf, hardscape, planting, irrigation, and drainage so the finished yard reads as a single design.",
        "card_meta": ("One plan covers", "Grading, drainage, irrigation, planting, hardscape, and lighting."),
        "faqs": [
            ("Can I hire just one service?", "Yes. Artificial grass, pavers, stepping stones, DG, irrigation, and fencing can each be quoted on their own. A full yard combines them under one project manager."),
            ("Do you use subcontractors?", "No. Turf, pavers, and concrete are installed by our own crews. That is how we control compaction, seams, and the final walkthrough instead of hoping a rotating crew shows up."),
            ("Are you a licensed landscape architect?", "No. Landscape designer work is design and install as a landscaper under contractor license #1122918. We do not claim a landscape-architect license."),
        ],
        "related": ["landscaper", "remodeller", "landscape-architect"],
        "closing_h2": "Ready to Price a Designed Yard?",
        "closing_p": "Tell us you want a full yard plan. We will walk the property and send a written scope for landscape design and installation in Encino. Call 818-297-2475 or request a free estimate.",
    },
    {
        "slug": "landscape-architect",
        "anchor": "architect",
        "nav": "Landscape architect",
        "h1": "Encino Landscape Design, Not a Landscape Architect License",
        "card_h3": "Landscape architect",
        "tag": "GBP only",
        "title": "Encino Landscaping Landscape Design | Landscape Designer",
        "description": "Encino landscape design from a licensed contractor, not a licensed landscape architect. Google category only. CSLB #1122918. Call 818-297-2475.",
        "h2_includes": "Encino Landscaping, Outdoor Living Space, Garden, and Backyard Layout",
        "h2_estimate": "Free Consultation for Encino Landscape Design",
        "h2_related": "Encino Work to Hire Instead of an Architect Claim",
        "cta_h2": "Request a Free Design Estimate",
        "highlights": [
            (
                "Google category only",
                "Landscape architect is a Google Business Profile label. It is not a claim that Option 1 Builders holds a landscape-architect license.",
            ),
            (
                "Contractor license #1122918",
                "The license on this site is California contractor license #1122918. You can verify that number with the CSLB.",
            ),
        ],
        "image": "project-05.jpg",
        "image_alt": "Residential Encino yard designed and installed by Option 1 Builders",
        "hero_sub": "Google lists Landscape architect as a category for this Encino landscaper. We design and install as a landscaper under contractor license #1122918. We do not claim a licensed landscape architect.",
        "lead": "Option 1 Builders designs and installs residential yards in Encino. The license we put on the walkthrough table is California contractor license #1122918, not a landscape-architect license. If you need a licensed landscape architect, that is a different credential than the one on this site.",
        "lead_more": [
            "The work we do under this Google label is the same design and install work described on the Landscaper and Landscape designer pages: one plan, one crew, written scope before demo.",
        ],
        "article_extra": [
            "Encino landscape design on this site is landscape design services in Encino from a contractor in Encino. A free consultation and a written estimate follow the walkthrough. Frequently asked questions about the license are below.",
            "Outdoor living and garden space get planned the same way as on the landscape designer page. Installation is by our own crews.",
        ],
        "blocks": [
            (
                "What we will not write",
                "We will not write licensed landscape architect, stamp architectural drawings as an architect, or invent a second license number. The CSLB number on the site is contractor #1122918.",
            ),
            (
                "Where to go next",
                "Hire the Encino landscaper page for the crew and irrigation work. Hire the landscape designer page for the one-plan yard. Both use facts already on this site.",
            ),
        ],
        "card_p": "A Google category only. We design and install as a landscaper under contractor license #1122918, not as a licensed landscape architect.",
        "card_meta": ("GBP label", "Design and install as a landscaper. No architect license claim."),
        "faqs": [
            ("Are you a licensed landscape architect?", "No. Google lists Landscape architect as a business category. Option 1 Builders is a licensed California contractor under #1122918. We design and install as a landscaper."),
            ("What license do you hold?", "California contractor license #1122918. You can verify that license with the CSLB. We hand you a copy of the license and insurance at the walkthrough."),
            ("Who should I call for a yard plan?", "Call 818-297-2475. We will walk the property and send a written scope for landscape design and installation. That is landscaper and landscape designer work, not an architect stamp."),
        ],
        "related": ["landscaper", "landscape-designer", "remodeller"],
        "closing_h2": "Need a Yard Plan, Not an Architect Stamp?",
        "closing_p": "Call 818-297-2475 or request a free estimate. We will walk your Encino property and write the design and install scope as a landscaper under license #1122918.",
    },
    {
        "slug": "construction-company",
        "anchor": "construction",
        "nav": "Construction Company",
        "h1": "Encino Hardscape for Outdoor Living and Pavers",
        "card_h3": "Construction Company",
        "tag": "Hardscape",
        "title": "Encino Landscape Hardscape CA | Paver Outdoor Living",
        "description": "Encino hardscape from this construction company: pavers, patio, driveway, walkway, fence, and outdoor living. Licensed. Call 818-297-2475.",
        "h2_includes": "Hardscaping Services From This Hardscape Contractor in CA",
        "h2_estimate": "Hardscape From Start to Finish for Encino Outdoor Living",
        "h2_related": "Other Encino Landscaping Quoted Beside This Hardscape",
        "cta_h2": "Request a Free Encino Hardscape Estimate",
        "highlights": [
            (
                "Concrete, DG, and gravel",
                "Decomposed granite patios, gravel beds, mulch, and poured concrete for clean, low-maintenance ground cover.",
            ),
            (
                "Vinyl fencing",
                "Vinyl fencing is a low-maintenance option for privacy and property lines. It can be quoted on its own or in a full yard.",
            ),
            (
                "Stepping stones",
                "Stone and paver pathways run through turf, gravel, or planting beds, with spacing planned to a natural stride.",
            ),
        ],
        "image": "project-11.jpg",
        "image_alt": "Decomposed granite patio, gravel beds, and a concrete walkway",
        "hero_sub": "Google lists Construction Company as a category. On this site that is outdoor hardscape: concrete, DG, gravel, stepping stones, and vinyl fencing.",
        "lead": "Option 1 Builders installs concrete, decomposed granite, gravel, mulch, stepping stones, and vinyl fencing in Encino. These finishes are for clean, low-maintenance ground cover and property lines, and can be quoted on their own.",
        "lead_more": [
            "DG is a crushed granite fine used for pathways, patios, and low-water areas. It compacts into a firm natural-looking surface, drains well, and pairs with pavers, stepping stones, and drought-tolerant planting. It is a common choice for Valley yards replacing lawn.",
        ],
        "article_extra": [
            "Encino hardscape on Ventura Blvd starts with a walkthrough. Outdoor living here is a patio, walkway, driveway, deck-level pavers, and a fence - not an outdoor kitchen or a water feature we do not list.",
            "A backyard remodel that needs a retaining wall, pool deck, or new backyard hardscape uses the same project manager. Landscape design and irrigation can be quoted beside this construction company work.",
            "Homeowners comparing Encino landscaping and Encino landscape design can hire hardscape on its own. Craftsmanship is compaction and a final walkthrough, not a Yelp slogan.",
        ],
        "blocks": [
            (
                "Concrete and ground cover",
                "Decomposed granite patios, gravel beds, mulch, and poured concrete. These can be quoted on their own or with a paving contractor patio.",
            ),
            (
                "Stepping stones and pathways",
                "Stone and paver pathways through turf, gravel, or planting beds, spaced to a natural stride. This work can be quoted on its own or as part of a full yard.",
            ),
            (
                "Vinyl fencing",
                "Vinyl fencing can be quoted on its own or included in a full yard project under one project manager.",
            ),
            (
                "In-house concrete crews",
                "Turf, pavers, and concrete are installed by our own crews. That is how we control compaction and the final walkthrough.",
            ),
        ],
        "card_p": "Concrete, decomposed granite, gravel, stepping stones, and vinyl fencing. Outdoor construction, not a general house builder.",
        "card_meta": ("What we build", "Hardscape finishes, pathways, and low-maintenance vinyl fencing."),
        "faqs": [
            ("What is decomposed granite (DG)?", "DG is a crushed granite fine used for pathways, patios, and low-water areas. It compacts into a firm natural-looking surface, drains well, and pairs with pavers, stepping stones, and drought-tolerant planting. It is a common choice for Valley yards replacing lawn."),
            ("Do you install vinyl fencing?", "Yes. Vinyl fencing is one of our services and is a low-maintenance option for privacy and property lines. It can be quoted on its own or included in a full yard project."),
            ("Can I hire just one service?", "Yes. Artificial grass, pavers, stepping stones, DG, irrigation, and fencing can each be quoted on their own. A full yard combines them under one project manager."),
            ("Do you build houses?", "No. Construction Company on this site means outdoor hardscape: concrete, DG, gravel, pathways, and vinyl fencing. We are a landscaping and hardscape contractor, license #1122918."),
        ],
        "related": ["paving-contractor", "landscaper", "turf-and-soil-supplier"],
        "closing_h2": "Ready to Price Encino Hardscape?",
        "closing_p": "Tell us whether you need concrete, DG, a pathway, or vinyl fencing. We will walk the property and send a written scope. Call 818-297-2475 or request a free estimate.",
    },
]

apply_extra(SERVICES)
